---
- hosts: launched
  become: true
  remote_user: fedora
  gather_facts: false
  tasks:
    - user: name=fedora groups=root append=yes

- name: Pull openshift/origin Image
  shell: docker pull openshift/origin

- name: Run openshift/origin as Docker Container
  shell: sudo docker run --name="origins" --privileged --net=host -e sysimage=/host -v /:/host -v /dev:/dev -v /run:/run -id openshift/origin start

- name: Run Cockpit
  shell: sudo docker run -ti --privileged -d --net=host -e sysimage=/host -v /:/host -v /dev:/dev -v /run:/run rhel7-cockpit

# When complete "kubectl cluster-info"
# Start the server:
#$ oc cluster up
#starts OpenShift Origin listening on local interface on your host (127.0.0.1:8443),
#starts the web console listening on all interfaces at /console (127.0.0.1:8443),
#launches the Kubernetes system components, and provisions registry, router, initial templates, and a default project.


if [ -f /etc/redhat-release ]; then
OS="Red Hat"
echo Deploying Openshift Origins
sudo usermod -aG root fedora
sudo su - $USER
sudo docker run --name="origin" -t -d -h=origin --privileged=true -p 8443:8443 -p 53:53 openshift/origin start
else
echo "Not RedHat"
fi



